name: mlops_project
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython_genutils=0.2.0
  - flake8=3.9.2
  - flake8-docstrings=1.6.0
  - black=21.5b2
  - pre-commit=2.13.0
